const express = require('express');
const router = express.Router();
const db = require('../config/db');
const logger = require('../utils/logger');
const { authenticateToken, requirePermission } = require('../middleware/auth');
const { logAudit } = require('../utils/auditLogger');
const ExcelJS = require('exceljs');

const formatWorksheet = (worksheet, title, user, filters = {}) => {
  worksheet.addRow(['NKB IT Management System - Analytical Report']);
  worksheet.addRow([`Report Title: ${title}`]);
  worksheet.addRow([`Generated by: ${user.username} on ${new Date().toLocaleString()}`]);
  
  if (Object.keys(filters).length > 0) {
    const filterStrings = Object.entries(filters)
      .filter(([_, v]) => v !== undefined && v !== '')
      .map(([k, v]) => `${k}: ${v}`)
      .join(' | ');
    if (filterStrings) worksheet.addRow([`Filters Applied: ${filterStrings}`]);
  }
  
  worksheet.addRow([]);

  worksheet.getRow(1).font = { bold: true, size: 14 };
  worksheet.getRow(2).font = { italic: true };
};

const formatHeaders = (worksheet, rowNum) => {
  const row = worksheet.getRow(rowNum);
  row.font = { color: { argb: 'FFFFFFFF' }, bold: true };
  row.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0F172A' } };
  row.alignment = { vertical: 'middle', horizontal: 'center' };
};

const autoFitColumns = (worksheet) => {
  worksheet.columns.forEach(column => {
    let maxLen = 0;
    column.eachCell({ includeEmpty: true }, cell => {
      const valStr = cell.value ? cell.value.toString() : '';
      if (valStr.length > maxLen) maxLen = valStr.length;
    });
    column.width = Math.max(maxLen + 2, 10);
  });
};

const createExportRoute = (path, title, perm, fetcher, headers, rowMapper) => {
  router.get(`/${path}`, authenticateToken, requirePermission(perm), async (req, res) => {
    try {
      const data = await fetcher(req);
      return res.json({ success: true, data });
    } catch (err) {
      logger.error(`Get ${path} report error: ${err.message}`);
      return res.status(500).json({ success: false, message: 'Failed to generate report.' });
    }
  });

  router.get(`/${path}/export`, authenticateToken, requirePermission('reports.export'), async (req, res) => {
    try {
      const data = await fetcher(req);
      const workbook = new ExcelJS.Workbook();
      const worksheet = workbook.addWorksheet(title.substring(0, 31));

      formatWorksheet(worksheet, title, req.user, req.query);
      
      const headerIndex = 5;
      worksheet.addRow(headers);
      formatHeaders(worksheet, headerIndex);

      data.forEach(item => worksheet.addRow(rowMapper(item)));
      
      worksheet.addRow([]);
      const totalRow = worksheet.addRow([`TOTAL RECORDS: ${data.length}`]);
      totalRow.font = { bold: true };

      autoFitColumns(worksheet);

      res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
      res.setHeader('Content-Disposition', `attachment; filename=${path}_Report.xlsx`);
      await workbook.xlsx.write(res);
      res.end();
      await logAudit(req, { action: `Export ${title}`, module: 'Reports' });
    } catch (err) {
      logger.error(`Export ${path} Excel error: ${err.message}`);
      return res.status(500).json({ success: false, message: 'Failed to export report.' });
    }
  });
};

// 1. BACKUPS
createExportRoute('backups', 'Data Backups Report', 'backups.view', 
  async (req) => {
    const q = db('data_backups').whereNull('deleted_at');
    if (req.query.status) q.where('status', req.query.status);
    return q.orderBy('created_at', 'desc');
  },
  ['Job Name', 'Backup Type', 'Storage', 'Size (MB)', 'Status', 'Verification', 'Created'],
  (i) => [i.job_name, i.backup_type, i.storage_location, i.size_mb, i.status, i.verification_status, i.created_at]
);

// 2. ENDPOINTS (OS)
createExportRoute('os', 'Operating Systems Report', 'endpoint_security.view',
  async (req) => {
    const q = db('operating_systems').join('assets', 'operating_systems.asset_id', 'assets.id')
      .select('operating_systems.*', 'assets.name as asset_name').whereNull('operating_systems.deleted_at');
    if (req.query.status) q.where('operating_systems.activation_status', req.query.status);
    return q.orderBy('operating_systems.hostname', 'asc');
  },
  ['Hostname', 'Asset', 'OS Name', 'Edition', 'Version', 'Activation Status'],
  (i) => [i.hostname, i.asset_name, i.os_name, i.edition, i.version, i.activation_status]
);

// 3. ENDPOINTS (AV)
createExportRoute('antivirus', 'Antivirus Tracking Report', 'endpoint_security.view',
  async (req) => {
    const q = db('antivirus_tracking').join('assets', 'antivirus_tracking.asset_id', 'assets.id')
      .select('antivirus_tracking.*', 'assets.name as asset_name').whereNull('antivirus_tracking.deleted_at');
    if (req.query.status) q.where('antivirus_tracking.scan_result', req.query.status);
    return q.orderBy('antivirus_tracking.hostname', 'asc');
  },
  ['Hostname', 'Asset', 'AV Name', 'Version', 'Last Scan', 'Scan Result', 'Next Scan'],
  (i) => [i.hostname, i.asset_name, i.antivirus_name, i.version, i.last_scan_date, i.scan_result, i.next_scan_date]
);

// 4. NETWORK DEVICES
createExportRoute('network-devices', 'Network Devices Report', 'network.view',
  async (req) => {
    const q = db('network_devices').whereNull('deleted_at');
    if (req.query.status) q.where('status', req.query.status);
    return q.orderBy('device_name', 'asc');
  },
  ['Device Name', 'Type', 'Brand', 'Model', 'Status', 'Location'],
  (i) => [i.device_name, i.device_type, i.brand, i.model, i.status, i.location]
);

// 5. WIFI APs
createExportRoute('wifi', 'WiFi Access Points Report', 'network.view',
  async (req) => {
    const q = db('wifi_access_points').whereNull('deleted_at');
    if (req.query.status) q.where('status', req.query.status);
    return q.orderBy('ap_name', 'asc');
  },
  ['AP Name', 'SSID', 'Brand', 'Model', 'Location', 'Status'],
  (i) => [i.ap_name, i.ssid, i.brand, i.model, i.location, i.status]
);

// 6. PRINTERS
createExportRoute('printers', 'Printers Report', 'printers.view',
  async (req) => {
    const q = db('printers').whereNull('deleted_at');
    if (req.query.status) q.where('status', req.query.status);
    return q.orderBy('printer_name', 'asc');
  },
  ['Printer Name', 'Brand', 'Model', 'Toner/Ink Type', 'Location', 'Status'],
  (i) => [i.printer_name, i.brand, i.model, i.toner_ink_type, i.location, i.status]
);

// 7. FILE SHARES
createExportRoute('file-shares', 'File Shares Report', 'file_shares.view',
  async (req) => {
    const q = db('file_shares').whereNull('deleted_at');
    return q.orderBy('folder_name', 'asc');
  },
  ['Folder Name', 'Server Location', 'Description', 'Quota (GB)', 'Created'],
  (i) => [i.folder_name, i.server_location, i.description, i.allocated_quota_gb, i.created_at]
);

// 8. GUEST WIFI
createExportRoute('guest-wifi', 'Guest WiFi Report', 'guest_wifi.view',
  async (req) => {
    const q = db('guest_wifi_accounts').whereNull('deleted_at');
    if (req.query.status) q.where('status', req.query.status);
    return q.orderBy('start_date', 'desc');
  },
  ['Guest Name', 'Company', 'Username', 'Start Date', 'End Date', 'Status'],
  (i) => [i.guest_name, i.company_name, i.wifi_username, i.start_date, i.end_date, i.status]
);

// 9. WEBSITES
createExportRoute('websites', 'Websites Report', 'websites.view',
  async (req) => {
    const q = db('website_monitoring').whereNull('deleted_at');
    if (req.query.status) q.where('status', req.query.status);
    return q.orderBy('name', 'asc');
  },
  ['Website Name', 'Domain', 'Host', 'SSL Expiry', 'Status', 'Last Checked'],
  (i) => [i.name, i.domain, i.hosting_provider, i.ssl_expiry_date, i.status, i.last_checked_at]
);

module.exports = router;
