const express = require('express');
const router = express.Router();
const db = require('../config/db');
const logger = require('../utils/logger');
const { authenticateToken, requirePermission } = require('../middleware/auth');
const { logAudit } = require('../utils/auditLogger');
const ExcelJS = require('exceljs');

// Helper: Setup Standard Excel Styles
const formatWorksheet = (worksheet, title, user, filters = {}) => {
  worksheet.addRow(['NKB IT Management System - Analytical Report']);
  worksheet.addRow([`Report Title: ${title}`]);
  worksheet.addRow([`Generated by: ${user.username} on ${new Date().toLocaleString()}`]);
  
  if (Object.keys(filters).length > 0) {
    const filterStrings = Object.entries(filters)
      .filter(([_, v]) => v !== undefined && v !== '')
      .map(([k, v]) => `${k}: ${v}`)
      .join(' | ');
    if (filterStrings) worksheet.addRow([`Filters Applied: ${filterStrings}`]);
  }
  
  worksheet.addRow([]); // empty space

  worksheet.getRow(1).font = { bold: true, size: 14 };
  worksheet.getRow(2).font = { italic: true };
};

const formatHeaders = (worksheet, rowNum) => {
  const row = worksheet.getRow(rowNum);
  row.font = { color: { argb: 'FFFFFFFF' }, bold: true };
  row.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF0F172A' } // Navy blue
  };
  row.alignment = { vertical: 'middle', horizontal: 'center' };
};

const autoFitColumns = (worksheet) => {
  worksheet.columns.forEach(column => {
    let maxLen = 0;
    column.eachCell({ includeEmpty: true }, cell => {
      const valStr = cell.value ? cell.value.toString() : '';
      if (valStr.length > maxLen) maxLen = valStr.length;
    });
    column.width = Math.max(maxLen + 2, 10);
  });
};

// ==========================================
// 1. ASSET MASTER LIST REPORT
// ==========================================
router.get('/assets', authenticateToken, requirePermission('reports.view'), async (req, res) => {
  const { categoryId, status, condition, startDate, endDate } = req.query;

  try {
    const query = db('assets')
      .join('asset_categories', 'assets.category_id', 'asset_categories.id')
      .leftJoin('departments', 'assets.department_id', 'departments.id')
      .leftJoin('employees', 'assets.employee_id', 'employees.id')
      .select(
        'assets.asset_code', 'assets.name', 'assets.brand', 'assets.model', 'assets.serial_number',
        'asset_categories.name as category_name', 'assets.condition', 'assets.status',
        'departments.name as department_name',
        db.raw("concat(employees.first_name, ' ', employees.last_name) as employee_name"),
        'assets.purchase_price', 'assets.purchase_date', 'assets.warranty_end_date'
      );

    if (categoryId) query.where('assets.category_id', categoryId);
    if (status) query.where('assets.status', status);
    if (condition) query.where('assets.condition', condition);
    if (startDate) query.where('assets.purchase_date', '>=', startDate);
    if (endDate) query.where('assets.purchase_date', '<=', endDate);

    const data = await query.orderBy('assets.asset_code', 'asc');
    return res.json({ success: true, data });
  } catch (err) {
    logger.error(`Get assets report error: ${err.message}`);
    return res.status(500).json({ success: false, message: 'Failed to generate asset report.' });
  }
});

// Export assets Excel
router.get('/assets/export', authenticateToken, requirePermission('reports.export'), async (req, res) => {
  const { categoryId, status, condition, startDate, endDate } = req.query;

  try {
    const query = db('assets')
      .join('asset_categories', 'assets.category_id', 'asset_categories.id')
      .leftJoin('departments', 'assets.department_id', 'departments.id')
      .leftJoin('employees', 'assets.employee_id', 'employees.id')
      .select(
        'assets.asset_code', 'assets.name', 'assets.brand', 'assets.model', 'assets.serial_number',
        'asset_categories.name as category_name', 'assets.condition', 'assets.status',
        'departments.name as department_name',
        db.raw("concat(employees.first_name, ' ', employees.last_name) as employee_name"),
        'assets.purchase_price', 'assets.purchase_date', 'assets.warranty_end_date'
      );

    if (categoryId) query.where('assets.category_id', categoryId);
    if (status) query.where('assets.status', status);
    if (condition) query.where('assets.condition', condition);
    if (startDate) query.where('assets.purchase_date', '>=', startDate);
    if (endDate) query.where('assets.purchase_date', '<=', endDate);

    const data = await query.orderBy('assets.asset_code', 'asc');

    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('Assets_Report');

    formatWorksheet(worksheet, 'Asset Master List', req.user, { categoryId, status, condition });

    // Header Row
    const headerIndex = 5;
    worksheet.addRow([
      'Asset Code', 'Asset Name', 'Category', 'Brand', 'Model',
      'Serial Number', 'Condition', 'Status', 'Department',
      'Assigned Employee', 'Purchase Price', 'Purchase Date', 'Warranty End'
    ]);
    formatHeaders(worksheet, headerIndex);

    let totalPrice = 0;
    data.forEach(item => {
      totalPrice += Number(item.purchase_price) || 0;
      worksheet.addRow([
        item.asset_code,
        item.name,
        item.category_name,
        item.brand,
        item.model,
        item.serial_number,
        item.condition,
        item.status,
        item.department_name || '',
        item.employee_name || '',
        Number(item.purchase_price) || 0,
        item.purchase_date || '',
        item.warranty_end_date || ''
      ]);
    });

    // Total Row
    worksheet.addRow([]);
    const totalRow = worksheet.addRow(['TOTAL ASSETS VALUE', '', '', '', '', '', '', '', '', '', totalPrice]);
    totalRow.font = { bold: true };

    autoFitColumns(worksheet);

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', 'attachment; filename=Asset_Report.xlsx');

    await workbook.xlsx.write(res);
    res.end();

    await logAudit(req, { action: 'Export Asset Report', module: 'Reports' });

  } catch (err) {
    logger.error(`Export assets Excel error: ${err.message}`);
    return res.status(500).json({ success: false, message: 'Failed to export assets report.' });
  }
});

// ==========================================
// 2. HELP DESK TICKETS REPORT
// ==========================================
router.get('/tickets', authenticateToken, requirePermission('reports.view'), async (req, res) => {
  const { categoryId, status, priority, technicianId, startDate, endDate } = req.query;

  try {
    const query = db('tickets')
      .join('ticket_categories', 'tickets.category_id', 'ticket_categories.id')
      .join('employees as req', 'tickets.requested_by_employee_id', 'req.id')
      .leftJoin('users as tech', 'tickets.assigned_technician_id', 'tech.id')
      .select(
        'tickets.ticket_number', 'tickets.subject', 'ticket_categories.name as category_name',
        'tickets.priority', 'tickets.status', 
        db.raw("concat(req.first_name, ' ', req.last_name) as requested_by_name"),
        'tech.username as assigned_technician_name',
        'tickets.created_at', 'tickets.resolution_date', 'tickets.closed_date'
      );

    if (categoryId) query.where('tickets.category_id', categoryId);
    if (status) query.where('tickets.status', status);
    if (priority) query.where('tickets.priority', priority);
    if (technicianId) query.where('tickets.assigned_technician_id', technicianId);
    if (startDate) query.where('tickets.created_at', '>=', startDate);
    if (endDate) query.where('tickets.created_at', '<=', endDate);

    const data = await query.orderBy('tickets.created_at', 'desc');
    return res.json({ success: true, data });
  } catch (err) {
    logger.error(`Get tickets report error: ${err.message}`);
    return res.status(500).json({ success: false, message: 'Failed to generate tickets report.' });
  }
});

// Export tickets Excel
router.get('/tickets/export', authenticateToken, requirePermission('reports.export'), async (req, res) => {
  const { categoryId, status, priority, technicianId, startDate, endDate } = req.query;

  try {
    const query = db('tickets')
      .join('ticket_categories', 'tickets.category_id', 'ticket_categories.id')
      .join('employees as req', 'tickets.requested_by_employee_id', 'req.id')
      .leftJoin('users as tech', 'tickets.assigned_technician_id', 'tech.id')
      .select(
        'tickets.ticket_number', 'tickets.subject', 'ticket_categories.name as category_name',
        'tickets.priority', 'tickets.status', 
        db.raw("concat(req.first_name, ' ', req.last_name) as requested_by_name"),
        'tech.username as assigned_technician_name',
        'tickets.created_at', 'tickets.resolution_date', 'tickets.closed_date'
      );

    if (categoryId) query.where('tickets.category_id', categoryId);
    if (status) query.where('tickets.status', status);
    if (priority) query.where('tickets.priority', priority);
    if (technicianId) query.where('tickets.assigned_technician_id', technicianId);
    if (startDate) query.where('tickets.created_at', '>=', startDate);
    if (endDate) query.where('tickets.created_at', '<=', endDate);

    const data = await query.orderBy('tickets.created_at', 'desc');

    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('Tickets_Report');

    formatWorksheet(worksheet, 'Help Desk Tickets Report', req.user, { categoryId, status, priority });

    const headerIndex = 5;
    worksheet.addRow([
      'Ticket Number', 'Subject', 'Category', 'Priority', 'Status',
      'Requested By', 'Assigned Technician', 'Date Filed', 'Date Resolved', 'Date Closed'
    ]);
    formatHeaders(worksheet, headerIndex);

    data.forEach(item => {
      worksheet.addRow([
        item.ticket_number,
        item.subject,
        item.category_name,
        item.priority,
        item.status,
        item.requested_by_name,
        item.assigned_technician_name || '',
        new Date(item.created_at).toLocaleDateString(),
        item.resolution_date ? new Date(item.resolution_date).toLocaleDateString() : '',
        item.closed_date ? new Date(item.closed_date).toLocaleDateString() : ''
      ]);
    });

    autoFitColumns(worksheet);

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', 'attachment; filename=Tickets_Report.xlsx');

    await workbook.xlsx.write(res);
    res.end();

    await logAudit(req, { action: 'Export Tickets Report', module: 'Reports' });

  } catch (err) {
    logger.error(`Export tickets Excel error: ${err.message}`);
    return res.status(500).json({ success: false, message: 'Failed to export tickets report.' });
  }
});

// ==========================================
// 3. REPAIRS COST REPORT
// ==========================================
router.get('/repairs', authenticateToken, requirePermission('reports.view'), async (req, res) => {
  const { status, technicianId, startDate, endDate } = req.query;

  try {
    const query = db('repairs')
      .join('assets', 'repairs.asset_id', 'assets.id')
      .leftJoin('users as tech', 'repairs.technician_id', 'tech.id')
      .select(
        'repairs.repair_number', 'assets.name as asset_name', 'assets.asset_code',
        'repairs.reported_issue', 'repairs.status', 'tech.username as technician_username',
        'repairs.parts_cost', 'repairs.labor_cost', 'repairs.external_service_cost', 'repairs.total_repair_cost',
        'repairs.date_received', 'repairs.repair_completion_date'
      );

    if (status) query.where('repairs.status', status);
    if (technicianId) query.where('repairs.technician_id', technicianId);
    if (startDate) query.where('repairs.date_received', '>=', startDate);
    if (endDate) query.where('repairs.date_received', '<=', endDate);

    const data = await query.orderBy('repairs.date_received', 'desc');
    return res.json({ success: true, data });
  } catch (err) {
    logger.error(`Get repairs report error: ${err.message}`);
    return res.status(500).json({ success: false, message: 'Failed to generate repair report.' });
  }
});

// Export repairs Excel
router.get('/repairs/export', authenticateToken, requirePermission('reports.export'), async (req, res) => {
  const { status, technicianId, startDate, endDate } = req.query;

  try {
    const query = db('repairs')
      .join('assets', 'repairs.asset_id', 'assets.id')
      .leftJoin('users as tech', 'repairs.technician_id', 'tech.id')
      .select(
        'repairs.repair_number', 'assets.name as asset_name', 'assets.asset_code',
        'repairs.reported_issue', 'repairs.status', 'tech.username as technician_username',
        'repairs.parts_cost', 'repairs.labor_cost', 'repairs.external_service_cost', 'repairs.total_repair_cost',
        'repairs.date_received', 'repairs.repair_completion_date'
      );

    if (status) query.where('repairs.status', status);
    if (technicianId) query.where('repairs.technician_id', technicianId);
    if (startDate) query.where('repairs.date_received', '>=', startDate);
    if (endDate) query.where('repairs.date_received', '<=', endDate);

    const data = await query.orderBy('repairs.date_received', 'desc');

    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('Repairs_Report');

    formatWorksheet(worksheet, 'Repairs and Costs Report', req.user, { status });

    const headerIndex = 5;
    worksheet.addRow([
      'Repair Number', 'Asset Code', 'Asset Name', 'Reported Issue', 'Status',
      'Technician', 'Parts Cost (PHP)', 'Labor Cost (PHP)', 'External Cost (PHP)', 'Total Cost (PHP)',
      'Date Received', 'Date Completed'
    ]);
    formatHeaders(worksheet, headerIndex);

    let sumParts = 0, sumLabor = 0, sumExt = 0, sumTotal = 0;

    data.forEach(item => {
      const p = Number(item.parts_cost) || 0;
      const l = Number(item.labor_cost) || 0;
      const e = Number(item.external_service_cost) || 0;
      const t = Number(item.total_repair_cost) || 0;

      sumParts += p;
      sumLabor += l;
      sumExt += e;
      sumTotal += t;

      worksheet.addRow([
        item.repair_number,
        item.asset_code,
        item.asset_name,
        item.reported_issue,
        item.status,
        item.technician_username || '',
        p, l, e, t,
        item.date_received,
        item.repair_completion_date || ''
      ]);
    });

    // Total cost rows
    worksheet.addRow([]);
    const totalRow = worksheet.addRow(['GRAND TOTAL COSTS', '', '', '', '', '', sumParts, sumLabor, sumExt, sumTotal]);
    totalRow.font = { bold: true };

    autoFitColumns(worksheet);

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', 'attachment; filename=Repairs_Report.xlsx');

    await workbook.xlsx.write(res);
    res.end();

    await logAudit(req, { action: 'Export Repairs Cost Report', module: 'Reports' });

  } catch (err) {
    logger.error(`Export repairs Excel error: ${err.message}`);
    return res.status(500).json({ success: false, message: 'Failed to export repairs cost report.' });
  }
});

// ==========================================
// 4. SPARE PARTS INVENTORY REPORT
// ==========================================
router.get('/inventory', authenticateToken, requirePermission('reports.view'), async (req, res) => {
  const { categoryId, lowStock } = req.query;

  try {
    const query = db('inventory_items')
      .join('inventory_categories', 'inventory_items.category_id', 'inventory_categories.id')
      .select('inventory_items.*', 'inventory_categories.name as category_name');

    if (categoryId) query.where('inventory_items.category_id', categoryId);
    if (lowStock === 'true') {
      query.whereRaw('inventory_items.current_quantity <= inventory_items.minimum_stock');
    }

    const data = await query.orderBy('inventory_items.item_code', 'asc');
    return res.json({ success: true, data });
  } catch (err) {
    logger.error(`Get inventory report error: ${err.message}`);
    return res.status(500).json({ success: false, message: 'Failed to generate inventory report.' });
  }
});

// Export inventory Excel
router.get('/inventory/export', authenticateToken, requirePermission('reports.export'), async (req, res) => {
  const { categoryId, lowStock } = req.query;

  try {
    const query = db('inventory_items')
      .join('inventory_categories', 'inventory_items.category_id', 'inventory_categories.id')
      .select('inventory_items.*', 'inventory_categories.name as category_name');

    if (categoryId) query.where('inventory_items.category_id', categoryId);
    if (lowStock === 'true') {
      query.whereRaw('inventory_items.current_quantity <= inventory_items.minimum_stock');
    }

    const data = await query.orderBy('inventory_items.item_code', 'asc');

    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('Inventory_Report');

    formatWorksheet(worksheet, 'Spare Parts Inventory Report', req.user, { categoryId, lowStock });

    const headerIndex = 5;
    worksheet.addRow([
      'Item Code', 'Item Name', 'Category', 'Brand', 'Model',
      'Unit of Measure', 'Current Stock', 'Min Stock', 'Reorder Qty',
      'Unit Cost (PHP)', 'Storage Location', 'Status'
    ]);
    formatHeaders(worksheet, headerIndex);

    data.forEach(item => {
      worksheet.addRow([
        item.item_code,
        item.name,
        item.category_name,
        item.brand,
        item.model,
        item.unit_of_measure,
        item.current_quantity,
        item.minimum_stock,
        item.reorder_quantity,
        Number(item.unit_cost) || 0,
        item.storage_location || '',
        item.status
      ]);
    });

    autoFitColumns(worksheet);

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', 'attachment; filename=Inventory_Report.xlsx');

    await workbook.xlsx.write(res);
    res.end();

    await logAudit(req, { action: 'Export Inventory Report', module: 'Reports' });

  } catch (err) {
    logger.error(`Export inventory Excel error: ${err.message}`);
    return res.status(500).json({ success: false, message: 'Failed to export inventory report.' });
  }
});

module.exports = router;
